<?php/*
    YOU MAY PLAY WITH THIS HTML TO TEST WITH BOOTSTRAP. THE TEMPLATE HERE CALLS ALL THE BOOTSTRAP FILES FROM THE WEB
    LOCAL COPIES ARE KEPT TO UTILIZE THE IDE'S AUTOCOMPLETE FEATURE 'INTELLI-SENSE'.

*/
?>
<div class="container">
    <div class="well">
        <?php
$precheck = 1;
//object to manage sql connections
include 'bin/sqlConnector.php';

echo "<h3>Congratulations! Sequel and your configurations are setup correctly.</h3>";
?>
    </div>
</div>
