<?php
/**
 * Created by IntelliJ IDEA.
 * User: serrin
 * Date: 5/22/17
 * Time: 10:11 PM
 */
?>
<h2>About</h2>
<p>﻿Hello and welcome to the Orders.com web app. Please feel free to browse the site and test it's functionality please
    refer to our <a href="index.php?page=privacy">privacy</a> statement if you have any questions on privacy.
Orders.com is a project web site created by Kaplan University students to act as a fully functional website using PHP, HTML, JS, and CSS via the agile process in 4 2 week sprints ending roughly on 5/22/2017.
The foundation of the site uses <a href="http://getbootstrap.com" target="_blank">Bootstrap</a> as its core for responsive design.
Please note the original goal of the site is to allow users to create an account, display a catalogue of products and order products.
It supports user groups i.e. normal users and administrators. Administrators may add products to the catalogue and upload images
Users may create user accounts and orders and retrieve order information.</p>
<h3>Credits</h3>
<h4>Yenny Fernandez:</h4>
<ul>
    <li>Principle stakeholder</li>
    <li>HCI development</li>
    <li>HTML template designer</li>
    <li>SQL development</li>
    <li>JavaScript</li>
</ul>

<h4>Eric Bigelow:</h4>
<ul>
    <li>Key developer</li>
    <li>PHP</li>
    <li>HTML</li>
    <li>Form designer</li>
    <li>SQL</li>
    <li>JavaScript</li>
</ul>


