<!--
    This catalog code
-->
<div class="container">


    <!-- Carousel Header -->

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="3"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="img/patio.jpg" alt="Outdoor">
            </div>

            <div class="item">
                <img src="img/electronic.jpg" alt="Electronics">
            </div>

            <div class="item">
                <img src="img/household.jpeg" alt="Household appliances">
            </div>


        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <!--end carrusel -->

    <!-- Title -->
    <div class="row">
        <div class="col-lg-12">
            <h3>New Arrivals</h3>
        </div>
    </div>
    <!-- /.row -->

    <!-- Page Features -->
    <div class="row text-center">

        <div class="col-md-3 col-sm-6 hero-feature">
            <div class="thumbnail">
                <img src="http://placehold.it/800x500" alt="">
                <div class="caption">
                    <h3>Item #1</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                    <p>
                        <a href="test/checkout.html" class="btn btn-primary"><span class="glyphicon glyphicon-shopping-cart align-left" aria-hidden="true"></span></a> <a href="test/description.htm" class="btn btn-default">view</a>

                    </p>
                </div>

            </div>
        </div>


        <div class="col-md-3 col-sm-6 hero-feature">

            <div class="thumbnail">

                <img src="http://placehold.it/800x500" alt="">

                <div class="caption">

                    <h3>Item #2</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>

                    <p>

                        <a href="#" class="btn btn-primary"><span class="glyphicon glyphicon-shopping-cart align-left" aria-hidden="true"></span></a> <a href="#" class="btn btn-default">view</a>

                    </p>
                </div>
            </div>
        </div>

        <div class="col-md-3 col-sm-6 hero-feature">
            <div class="thumbnail">
                <img src="http://placehold.it/800x500" alt="">
                <div class="caption">
                    <h3>item #3</h3>
                    <p>Product Description
                        Price: $ 2.00 .</p>
                    <p>
                        <a href="#" class="btn btn-primary"><span class="glyphicon glyphicon-shopping-cart align-left" aria-hidden="true"></span></a> <a href="#" class="btn btn-default">view</a>
                    </p>
                </div>
            </div>
        </div>

        <div class="col-md-3 col-sm-6 hero-feature">
            <div class="thumbnail">
                <img src="http://placehold.it/800x500" alt="">
                <div class="caption">
                    <h3>item #4</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>

                    <p>
                        <a href="#" class="btn btn-primary"><span class="glyphicon glyphicon-shopping-cart align-left" aria-hidden="true"></span></a> <a href="#" class="btn btn-default">view</a>


                    </p>

                </div>
            </div>
        </div>

    </div>
    </body>
    <p class="text-center">&copy;2017 ACME Industries llc.</p>