<?php
/**
 * Created by IntelliJ IDEA.
 * User: serrin
 * Date: 5/21/17
 * Time: 9:50 PM
 */
?>
<h1>Download your copy of Orders.com checkout system below</h1>

<p> please note this package is provided in many compressed formats. To use the code download the compressed file of your
    choice. After downloading the source it will be necessary to download the zip or tarball of the SQL code as well.</p>
<h4>Orders.com source files.</h4>
<ul>
    <li class="downloadli">Download from <a href="https://github.com/ejbigelow/it488" target="_blank">Github</a></li>
    <ul>
        <li class="downloadli"><a href="download/Orders.com_source_code.zip">zip</a></li>
        <li class="downloadli"><a href="download/Orders.com_source_code.rar">rar</a></li>
        <li class="downloadli"><a href="download/Orders.com_source_code.tar.gz">tar.gz</a></li>
    </ul>
    <ul>
        <li class="downloadlimd5">MD5 (zip): ac6cc6434a9a0d00d3c21d15e7c1f4c8</li>
    </ul>
    <ul>
        <li class="downloadlimd5">MD5 (rar): 2f55a68e7f90bc8cf193b5af12b94e65</li>
    </ul>
    <ul>
        <li class="downloadlimd5">MD5 (tar.gz): b57eaf2c80a155dffb64e96b8fd1f700</li>
    </ul>

</ul>
<ul>
    <li class="downloadul">Orders.com SQL file.</li>
    <ul>
        <li class="downloadlimd5"><a href="download/Orders.com_sql.zip">zip</a></li>
        <li class="downloadli"><a href="download/Orders.com_sql.rar">rar</a></li>
        <li class="downloadli"><a href="download/Orders.com_sql.sql.tar.gz">tar</a></li>
    </ul>
    <ul>
        <li class="downloadlimd5">MD5 (zip): f59a74c7f9d1a828068ac4aecdc2c506</li>
    </ul>
    <ul>
        <li class="downloadlimd5">MD5 (rar): 961059d0074d9d97994c0a64533f59cc</li>
    </ul>
    <ul>
        <li class="downloadlimd5">MD5 (tar.gz): e415e9d1a45aa4e278960680935d5f77</li>
    </ul>

</ul>