<div class="jumbotron">
    <h1>Welcome to Order.com</h1>
    <h3>The one stop-shop for all your household needs</h3>

</div>
<div class="row center-block">
    <div class="col-lg-3 jumbotron text-center block1">
        household
    </div>
    <div class="col-lg-3 col-lg-offset-1 jumbotron block2">
        electronics
    </div>
    <div class="col-lg-3 col-lg-offset-1 jumbotron block3">
        outdoors
    </div>

</div>
