<?php
/**
 * Created by IntelliJ IDEA.
 * User: serrin
 * Date: 5/22/17
 * Time: 10:31 PM
 */
?>
<h2>Privacy</h2>
<p>This site uses many features that may gather information. These features include:</p>
<ul>
    <li>Submitted data</li>
    <li>Cookies</li>
    <li>Session Cookies, and</li>
    <li>server logs</li>
</ul>
<p>Please note: this is only retained for statistical and functionality. If you choose to create an account and test
    this site's full functionality you do so at your own risk and while only this site's administrators will see
    privileged information such as names, addresses, and email addresses submitted for account creation we ask that you at least
    use your real first and last name to verify integrity of the source.</p>
