<p class="text-center">&copy;2017 ACME Industries llc.</p>
<?php
echo "<div id=\"container\">\n<pre>\n";
var_dump($_SESSION['cart']);
var_dump($_SESSION['item0']);
var_dump($_SESSION['item1']);
var_dump($_SESSION['item2']);
var_dump($_SESSION['item3']);
var_dump($_SESSION['item4']);
var_dump($_SESSION['item5']);
var_dump($_SESSION['item6']);
var_dump($_SESSION['item7']);
var_dump($_SESSION['item8']);
var_dump($_SESSION['item9']);
echo "</pre>\n</div>";
?>
</body>
